server:
  port: 8090
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    # 自定义端口
    port: 6090
feign:
  client:
    config:
      default: # 这里的default表示对所有Feign客户端生效，如果你想为特定的服务配置，请替换default为服务名
        connectTimeout: 60000 # 连接超时时间，单位为毫秒 60秒
        readTimeout: 60000 # 读取超时时间，单位为毫秒 60秒
spring:
  application:
    name: forim-executor
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      file-size-threshold: 100MB
  jackson:
    # 使用 ISO 8601 格式
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  data:
    redis:
      password: ${FORIM_REDIS_PASSWORD}
      database: ${FORIM_REDIS_DATABASE}
      host: ${FORIM_REDIS_HOST}
      port: ${FORIM_REDIS_PORT}
      timeout: 5s
      connect-timeout: 3s
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 10s
forim:
  inner:
    assets:
      url: ${FORIM_GLOBAL_LB_ASSETS_SERVICE_URL}
    general:
      url: ${FORIM_GLOBAL_LB_GENERAL_SERVICE_URL}
    exchange:
      url: ${FORIM_GLOBAL_LB_EXCHANGE_SERVICE_URL}
    database:
      url: ${FORIM_GLOBAL_LB_DATABASE_SERVICE_URL}
    metadata:
      url: ${FORIM_GLOBAL_LB_METADATA_SERVICE_URL}
    schedule:
      url: ${FORIM_GLOBAL_LB_SCHEDULE_SERVICE_URL}

#日志
logging:
  level:
    cn.gov.forestry: ${FORIM_GLOBAL_LOGGING_LEVEL:debug}
